export const ABILITY_ROLL_UI = {
  pageTitle: 'Gerar atributos',
  pageHint: 'Métodos do livro (págs. 72–80) para definir os seis atributos base do herói.',
  pageNote: 'Bônus de cultura, virtudes e chamado são aplicados depois, na Criação e no Resumo.',
  methods: {
    roll: 'Rolagem 4d6',
    standardArray: 'Array padrão',
    pointBuy: 'Compra de pontos',
    manual: 'Manual',
  },
  rollHint: 'Role 4d6 seis vezes, descarte o menor dado de cada rolagem. Soma típica entre 72 e 80.',
  standardHint: 'Distribua 15, 14, 13, 12, 10 e 8 entre os atributos (soma 72).',
  pointBuyHint: '27 pontos no total · cada atributo entre 8 e 15.',
  manualHint: 'Digite os valores base diretamente (sem limite de pontos).',
  rollButton: 'Rolar seis atributos',
  reroll: 'Rolar de novo',
  resetArray: 'Recomeçar distribuição',
  resetPointBuy: 'Resetar pontos',
  resetManual: 'Voltar aos padrões',
  availablePool: 'Valores disponíveis',
  assignLabel: 'Atribuir',
  unassigned: '—',
  totalSum: 'Soma total',
  apply: 'Aplicar à ficha',
  applied: 'Atributos base salvos na ficha.',
  incomplete: 'Distribua todos os seis valores antes de aplicar.',
  pointsRemaining: 'pontos restantes',
  pointsSpent: 'gastos',
  costTable: 'Tabela de custos',
  lastRolls: 'Últimas rolagens',
  dropped: 'descartado',
} as const;

export type AbilityScoreGenMethod = keyof typeof ABILITY_ROLL_UI.methods;
