export const SHEET_PLAY_UI = {
  pageTitle: 'Ficha do herói',
  pageHint: 'Modo de jogo — ajuste PV, inspire-se e role ataques. Edite os blocos quando precisar mudar o personagem.',
  editSheet: 'Editar ficha',
  printSheet: 'Imprimir',
  exportPdf: 'Baixar PDF',
  exportPdfBusy: 'Gerando PDF…',
  exportPdfError: 'Erro ao gerar o PDF.',
  heroBadge: 'Em jogo',
  vitality: 'Vitalidade',
  combat: 'Combate',
  abilities: 'Atributos',
  saves: 'Resistências',
  skills: 'Perícias ativas',
  passiveWisdom: 'Sab. passiva',
  attacks: 'Ataques equipados',
  attacksHint: 'Armas do Inventário. Equipe no Inventário para aparecer aqui.',
  rollAttack: 'Ataque',
  rollDamage: 'Dano',
  reference: 'Consulta rápida',
  referenceHint: 'Equipamento, virtudes e crônica — só leitura na mesa.',
  equipment: 'Equipamento',
  virtues: 'Virtudes & traços',
  story: 'História',
  fellowship: 'Comunidade',
  appearance: 'Aparência',
  noSkills: 'Nenhuma perícia marcada na ficha.',
  inspiration: 'Inspiração',
  inspired: 'Inspirado',
} as const;
