/** Rótulos do shell da aplicação (header, footer, navegação). */

export const SHELL_UI = {
  appEyebrow: 'Ficha digital',
  appTitleShort: 'LOTR RPG',
  resetShort: 'Zerar',
  saveIdle: 'Salvo',
  saveBusy: 'Salvando…',
  saveHint: 'Dados guardados automaticamente no navegador',
  reset: 'Começar do zero',
  resetTitle: 'Começar do zero?',
  resetBody:
    'A ficha volta ao estado inicial: criação, atributos, inventário, moedas, história e notas serão apagados neste navegador.',
  resetBulletCreationPrefix: 'Você volta para a aba',
  resetBulletUndo: 'Não há como desfazer depois de confirmar',
  resetConfirm: 'Sim, começar do zero',
  cancel: 'Cancelar',
  modeBuilding: 'Montagem',
  modePlay: 'Em jogo',
  journeyLabel: 'Passos da ficha',
  journeySteps: (done: number, total: number) =>
    done === 1 ? `1/${total} passo` : `${done}/${total} passos`,
  goToSheet: 'Ir para a ficha',
  openSheet: 'Abrir ficha do herói',
  sheetReady: 'Ficha pronta para a mesa',
  finishHint: 'Complete os passos e abra a ficha para jogar.',
  characters: 'Personagens',
  charactersShort: 'Pers.',
  charactersTitle: 'Meus personagens',
  charactersHint: 'Troque, crie, exporte ou importe fichas — tudo salvo neste navegador.',
  charactersCount: (n: number) => (n === 1 ? '1 personagem' : `${n} personagens`),
  newCharacter: 'Novo personagem',
  switchCharacter: 'Abrir',
  deleteCharacter: 'Excluir',
  deleteConfirm: 'Excluir este personagem? Não há como desfazer.',
  exportJson: 'Exportar JSON',
  importJson: 'Importar JSON',
  importError: 'Não foi possível importar o arquivo.',
  activeCharacter: 'Ativo',
  tapToOpen: 'Toque para abrir',
  missingSteps: 'Falta completar',
  footerTitle: 'O Senhor dos Anéis RPG',
  footerSubtitle: 'Ficha digital de personagem',
  footerCredit: 'The One Ring™ · Free League Publishing',
  footerStorage: 'Progresso salvo localmente neste dispositivo',
} as const;

export const JOURNEY_STEP_LABELS = {
  creation: 'Criação',
  dice: 'Atributos',
  inventory: 'Inventário',
  story: 'História',
  summary: 'Ficha',
} as const;
